export interface PlayerPointsStat {
  bundesligaGoals: number;
  bundesligaAssits: number;
  bundesligaShotsOnGoals: number;
  bundesligaYellowCards: number;
  bundesligaRedCards: number;
  assists: number;
  causedPenalities: number;
  playedMinutes: number;
  goals: number;
  passesToShot: number;
  cleanSheet: number;
  penaltySaved: number;
  wonDuels: number;
  shotsOnGoal: number;
  shotsSaved: number;
  twoGoals: number;
  threeGoals: number;
  winningGoal: number;
  winningTeam: number;
  loosingTeam: number;
  goalsConceeded: number;
  yellowCard: number;
  secondYellowCard: number;
  redCard: number;
  ownGoals: number;
  missedPenalties: number;
  scoredPenalties: number;
}
